language: node_js
node_js:
  - 'lts/*'
cache: npm
install: true
script:
  - npm install
  - npm test
  - npm run test:coverage
  - npm build
on:
  branch: master
deploy:
  provider: surge
  skip_cleanup: true
  domain: resume-builder.surge.sh
  project: ./dist/